DATA TRD_Mnth (Label="月个股回报率文件");
Infile '/folders/myshortcuts/data/TRD_Mnth.txt' encoding="utf-8" delimiter = '09'x Missover Dsd lrecl=32767 firstobs=2;
Format Stkcd $6.;
Format Trdmnt $7.;
Format Opndt $10.;
Format Mopnprc 9.3;
Format Clsdt $10.;
Format Mclsprc 9.3;
Format Mnshrtrd 18.0;
Format Mnvaltrd 18.3;
Format Msmvosd 16.2;
Format Msmvttl 16.2;
Format Ndaytrd 2.0;
Format Mretwd 10.6;
Format Mretnd 10.6;
Format Markettype 10.0;
Format Capchgdt $10.;
Format Ahshrtrd_M 18.0;
Format Ahvaltrd_M 18.3;
Informat Stkcd $6.;
Informat Trdmnt $7.;
Informat Opndt $10.;
Informat Mopnprc 9.3;
Informat Clsdt $10.;
Informat Mclsprc 9.3;
Informat Mnshrtrd 18.0;
Informat Mnvaltrd 18.3;
Informat Msmvosd 16.2;
Informat Msmvttl 16.2;
Informat Ndaytrd 2.0;
Informat Mretwd 10.6;
Informat Mretnd 10.6;
Informat Markettype 10.0;
Informat Capchgdt $10.;
Informat Ahshrtrd_M 18.0;
Informat Ahvaltrd_M 18.3;
Label Stkcd="证券代码";
Label Trdmnt="交易月份";
Label Opndt="月开盘日期";
Label Mopnprc="月开盘价";
Label Clsdt="月收盘日期";
Label Mclsprc="月收盘价";
Label Mnshrtrd="月个股交易股数";
Label Mnvaltrd="月个股交易金额";
Label Msmvosd="月个股流通市值";
Label Msmvttl="月个股总市值";
Label Ndaytrd="月交易天数";
Label Mretwd="考虑现金红利再投资的月个股回报率";
Label Mretnd="不考虑现金红利再投资的月个股回报率";
Label Markettype="市场类型";
Label Capchgdt="最新股本变动日期";
Label Ahshrtrd_M="月盘后成交总量";
Label Ahvaltrd_M="月盘后成交总额";
Input Stkcd $ Trdmnt $ Opndt $ Mopnprc Clsdt $ Mclsprc Mnshrtrd Mnvaltrd Msmvosd Msmvttl Ndaytrd Mretwd Mretnd Markettype Capchgdt $ Ahshrtrd_M Ahvaltrd_M;
Run;
